name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1

      - name: Install Dependencies
        run: yarn install

      - name: Test
        uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          GITHUB_TOKEN: ${{ secrets.DEVELOPER_PAT_30_DAYS }}

      - name: Build
        run: yarn build



